[tasks.install-fonts]
description = "Fetch fonts from Google Fonts"
run = "./scripts/install-fonts.sh"

[tasks.mockgen]
description = "Generate a mock Kodi library"
run = "./scripts/mockgen.sh"

[tasks.symlink]
description = "Symlink the skin into Kodi's addons directory"
run = "./scripts/symlink.sh"
